### PR TITLE
Add support for multiple API endpoints

### LINKED ISSUE #7: Add support for more API endpoints
Add API support for accessing followers, following, star, and fork counts.

### PR DESCRIPTION
**Pull request by paramsiddharth**
Closes #7: **Add support for more API endpoints**
This version supports the following endpoints:
- `/users/:username/repos`
- `/users/:username/gists`
- `/users/:username/followers`
- `/users/:username/following`
- `/users/:username/starred`

~Additionally, the forked repositories are filtered into a separate array.~

_Sample response object:_
``` js
{
    "username": "paramsiddharth", // The entered username
    "repos": [repo1, repo2, ...], // An array of repo objects
    "gists": [gist1, gist2, ...],
    "followers": [follower1, follower2, ...],
    "following": [user1, user2, ...],
    "starred": [repo1, repo2, ...]
    // "forks": [fork1, fork2, ...] REMOVED
}
```

In case of a failed request, the corresponding attribute is set to `null`.
``` js
    ...
    "repos": null, // Failed request
    ...
```

I chained a `.catch(...)` at the end of the request chain to properly log other network-related errors to the prompt.

### CODE REVIEW

**Comment by adityabisoi** [comment]
@paramsiddharth Please use GitHub contribution guidelines when making a PR https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references
Use `close` or `closes` to automatically close the issue related to the PR.

**Comment by paramsiddharth** [comment]
@adityabisoi Thank you! I updated the PR with the `Closes` keyword.

**Comment by adityabisoi** [comment]
@paramsiddharth I think, we can remove the unnecessary `forks` for now. The data returned is large and redundant.

**Comment by paramsiddharth** [comment]
> @paramsiddharth I think, we can remove the unnecessary `forks` for now. The data returned is large and redundant.

Done! Now the response object contains only the username and the data obtained from the 5 endpoints.

**Pull request merged**
