### PR TITLE
Adysis14 patch 1 1

### PR DESCRIPTION
**Pull request by adysis14**
# Related Issue
- add Badges
- add Table of Contents
- beautify README.md

# Proposed Changes
- Added Badges in README.md
- Added Table of Contents in README.md
- Beautified README.md
- change 2

# Checklist
- [ ] Add Badges
- [ ] Add Table of Contents
- [ ] Beautify README.md

# Screenshots

      | Original        
:--------------------------:|:-----------------------:
Screenshot (14)

Screenshot (15)

      |  Updated
:--------------------------:|:-----------------------:

Screenshot (11)

Screenshot (12)

Screenshot (13)

### CODE REVIEW

**Comment by adityabisoi** [comment]
Few caveats:
* Please remove the picture in the middle.
* Add proper links in `Table of Contents`
* Remove centering from all the components (Let them stick to the left as always)

**Comment by adysis14** [comment]
@adityabisoi  can you please recheck this?

**Comment by adysis14** [comment]
@adityabisoi if you are satisfied with these changes then please award me points for this under NWOC

**Comment by adityabisoi** [comment]
Sure, one thing- you need to change the table of contents and write the headings of README instead of the questions, and point to the headings.
For example,
* [Linting](https://github.com/adityabisoi/github-rest-api-v3/blob/2d01ee9bfc0cc1a585f3b957d51160fa34e13f31/README.md#-linting)

**Comment by adysis14** [comment]
Can i do it tomorrow morning? Will that be counted?

**Comment by adityabisoi** [comment]
Sure, it will be.

**Comment by adysis14** [comment]
@adityabisoi can you please recheck this?

**Pull request merged**
