### PR TITLE
Issue #52

### PR DESCRIPTION
**Pull request by SedaII**
# Related Issue
The profile endpoint has been forgotten in the Github.js from 'Recover lost pagination update' #52

# Proposed Changes
- Added profile endpoint
- Added No repos/followers/following condition

# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentation

### CODE REVIEW

**Comment by adityabisoi** [comment]
The compare users at `http://localhost:3000/github-rest-api-v3/compare` shows an error.

**Comment by SedaII** [comment]
Didn't think about correcting the comparing component as well

**Comment by SedaII** [comment]
Do I have to cancel this PR and do another one?

**Comment by SedaII** [comment]
@adityabisoi I've corrected the issue

**Pull request merged**
