### PR TITLE
[Fixes #6] Added github star and fork buttons

### LINKED ISSUE #6: Add GitHub Star and Fork buttons
Add a `Star` and `Fork` button to the homepage

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
# Related Issue
- fixes #6 

# Proposed Changes
- I have made changes in header.js by adding github buttons

# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentation

# Screenshots

Original              |  Updated
:--------------------------:|:-----------------------:
** 
new
 **   |  ** 
old
 **

### CODE REVIEW

**Comment by adityabisoi** [comment]
@Vrindagupta6828 update with the new changes.

**Comment by Vrindagupta6828** [comment]
@adityabisoi what are the new changes?

**Comment by adityabisoi** [comment]
There's a header added. Place the buttons on the header on the left side of `Compare users` button.

**Comment by Vrindagupta6828** [comment]
Capture
@adityabisoi Will this work? If yes please merge my pr

**Comment by Vrindagupta6828** [comment]
@adityabisoi Do i have to do anything else?

**Comment by adityabisoi** [comment]
@Vrindagupta6828 As I said, You have added the buttons on an empty page where there is no header.

Suggestion: Delete this PR and your local branch. Checkout to `main`, pull latest changes. Add the same two lines for buttons just beside `Compare Users` in `header.js` and checkout to a new branch, and finally push it.

**Comment by Vrindagupta6828** [comment]
@adityabisoi I added it just before the compare users button but still they are not coming beside compare users

**Comment by Vrindagupta6828** [comment]
can you suggest anything?

**Comment by adityabisoi** [comment]
@Vrindagupta6828 I just suggested you above. That is the most detailed solution I could provide

**Comment by Vrindagupta6828** [comment]
@adityabisoi I have added in the navbar header

**Comment by adityabisoi** [comment]
Closing this PR. Please take up a different one.

**Comment by Vrindagupta6828** [comment]
@adityabisoi I have been working on it since a long time atleast give me one more chance

**Pull request closed without merging**
