### PR TITLE
Added Issue template for bug reports

### LINKED ISSUE #3: Add issue template: bug report
Add an issue template for reporting bugs in the project.

### PR DESCRIPTION
**Pull request by Halix267**
closes #3 
Added Issue template for bug reports.

### CODE REVIEW

**Comment by Halix267** [comment]
Hey @adityabisoi .Plzz review my PR.

**Comment by adityabisoi** [comment]
@Halix267 Please provide a proper PR name. Use `closes` as in `closes #3` in the PR description.

**Comment by Halix267** [comment]
@adityabisoi Done :). Any more changes?

**Comment by Halix267** [comment]
@adityabisoi when will u assign the points of this pr.

**Pull request merged**
