### PR TITLE
Fix: Issue #20 Fixed, icon and title changed.

### LINKED ISSUE #20: Change page title and icon
Currently, the page title and icon are set to React default.

Screenshot from 2020-12-02 11-39-50

 Change the title to the project name, and the icon to the GitHub logo.

### PR DESCRIPTION
**Pull request by prabhat04011998**
# Related Issue
Closes #20 Change page title and icon.

# Proposed Changes
- Default react icon changed to github icon
- Title changed to Name of the project.

# Additional Info
- No additional info , it's a basic issue

# Checklist
- [x] Tests
- [x] Translations
- [x] Documentation

# Screenshots

Original              |  Updated
:--------------------------:|:-----------------------:
** original screenshot **   | image

### CODE REVIEW

**Comment by adityabisoi** [comment]
@prabhat04011998 you need to comment on the issue first and work on it only after you are assigned.

**Comment by prabhat04011998** [comment]
@adityabisoi  i'll take care of it,you can assign it to me.

**Comment by adityabisoi** [comment]
Use GitHub contribution guidelines when making a PR https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references
Use close or closes to automatically close the issue related to the PR.

**Comment by prabhat04011998** [comment]
@adityabisoi  Okay thanks , done with it.

**Pull request merged**
